// Generated by gencpp from file add_markers/markerReady.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_MARKERREADY_H
#define ADD_MARKERS_MESSAGE_MARKERREADY_H

#include <ros/service_traits.h>


#include <add_markers/markerReadyRequest.h>
#include <add_markers/markerReadyResponse.h>


namespace add_markers
{

struct markerReady
{

typedef markerReadyRequest Request;
typedef markerReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct markerReady
} // namespace add_markers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_markers::markerReady > {
  static const char* value()
  {
    return "fdff9e8065741781036b62dff308d310";
  }

  static const char* value(const ::add_markers::markerReady&) { return value(); }
};

template<>
struct DataType< ::add_markers::markerReady > {
  static const char* value()
  {
    return "add_markers/markerReady";
  }

  static const char* value(const ::add_markers::markerReady&) { return value(); }
};


// service_traits::MD5Sum< ::add_markers::markerReadyRequest> should match 
// service_traits::MD5Sum< ::add_markers::markerReady > 
template<>
struct MD5Sum< ::add_markers::markerReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_markers::markerReady >::value();
  }
  static const char* value(const ::add_markers::markerReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_markers::markerReadyRequest> should match 
// service_traits::DataType< ::add_markers::markerReady > 
template<>
struct DataType< ::add_markers::markerReadyRequest>
{
  static const char* value()
  {
    return DataType< ::add_markers::markerReady >::value();
  }
  static const char* value(const ::add_markers::markerReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_markers::markerReadyResponse> should match 
// service_traits::MD5Sum< ::add_markers::markerReady > 
template<>
struct MD5Sum< ::add_markers::markerReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_markers::markerReady >::value();
  }
  static const char* value(const ::add_markers::markerReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_markers::markerReadyResponse> should match 
// service_traits::DataType< ::add_markers::markerReady > 
template<>
struct DataType< ::add_markers::markerReadyResponse>
{
  static const char* value()
  {
    return DataType< ::add_markers::markerReady >::value();
  }
  static const char* value(const ::add_markers::markerReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_MARKERREADY_H
