// Generated by gencpp from file add_markers/markerReadyRequest.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_MARKERREADYREQUEST_H
#define ADD_MARKERS_MESSAGE_MARKERREADYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_markers
{
template <class ContainerAllocator>
struct markerReadyRequest_
{
  typedef markerReadyRequest_<ContainerAllocator> Type;

  markerReadyRequest_()
    : ready(0)  {
    }
  markerReadyRequest_(const ContainerAllocator& _alloc)
    : ready(0)  {
  (void)_alloc;
    }



   typedef int64_t _ready_type;
  _ready_type ready;





  typedef boost::shared_ptr< ::add_markers::markerReadyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_markers::markerReadyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct markerReadyRequest_

typedef ::add_markers::markerReadyRequest_<std::allocator<void> > markerReadyRequest;

typedef boost::shared_ptr< ::add_markers::markerReadyRequest > markerReadyRequestPtr;
typedef boost::shared_ptr< ::add_markers::markerReadyRequest const> markerReadyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_markers::markerReadyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_markers::markerReadyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace add_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::markerReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::markerReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::markerReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::markerReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::markerReadyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::markerReadyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_markers::markerReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d74ca1ffb31881ab824e1d61313924a0";
  }

  static const char* value(const ::add_markers::markerReadyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd74ca1ffb31881abULL;
  static const uint64_t static_value2 = 0x824e1d61313924a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::add_markers::markerReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_markers/markerReadyRequest";
  }

  static const char* value(const ::add_markers::markerReadyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_markers::markerReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ready\n\
";
  }

  static const char* value(const ::add_markers::markerReadyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_markers::markerReadyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ready);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct markerReadyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_markers::markerReadyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_markers::markerReadyRequest_<ContainerAllocator>& v)
  {
    s << indent << "ready: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ready);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_MARKERREADYREQUEST_H
